name: Retry Release from Existing Artifacts

on:
  workflow_dispatch:
    inputs:                 # 定义输入参数
      run-id:          # 运行ID
        description: '运行ID'
        required: true
        type: string        # 参数类型：字符串
      tag:
        description: '要发布的标签名'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        pattern: "bin-*"
        path: ./
        merge-multiple: true
        run-id: ${{ inputs.run-id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to Release
      id: upload_to_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.tag }}
        files: "*.7z"